name: ToDo App Pipeline

on:
  push:
    branches:
    - main

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the files
      uses: actions/checkout@v2

    - name: Start SSH agent
      run: |
        eval $(ssh-agent -s)
        mkdir -p ~/.ssh  # Create the .ssh directory if it doesn't exist
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Debug SSH Key
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "echo SSH connection successful"
      
    

    - name: Deploy to EC2
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: /var/www/html
        SOURCE: ./
        SCRIPT_AFTER: |
          sudo systemctl restart apache2
        